package com.avalancherush.game.Enums;

public enum EventType {
    VOLUME_DOWN,
    VOLUME_UP,
    SLIDED_LEFT,
    SLIDED_RIGHT,
    SLIDED_UP,
    SINGLE_PLAYER_BUTTON_CLICK,
    MULTIPLAYER_BUTTON_CLICK,
    SETTINGS_BUTTON_CLICK,
    PROFILE_BUTTON_CLICK,
}
